import getImage from '@/app/functions/getImage';
import Feeds from '@/components/feeds';
import { ImagePage } from '@/components/image-page';

let x;

function generateMetadata(imageUrl, title = " AI Image Generator", description = "Images Generated by SopAI - AI Image Generator",url) {
  return {
    "@context": "https://schema.org",
    "@type": "WebPage",
    "url": url || null,
    "name": title,
    "description": description,
    "image": imageUrl,
    "author": {
      "@type": "Person",
      "name": "Your Name or Company Name"
    },
    "publisher": {
      "@type": "Organization",
      "name": "SopAI",
      "logo": {
        "@type": "ImageObject",
        "url": "/logo.png"
      }
    },
    "inLanguage": "en-US",
    "mainEntityOfPage": {
      "@type": "WebPage",
      "@id": url || null
    },
    "openGraph": {
      "type": "website",
      "url": url || null,
      "title": title,
      "description": description,
      "images": [{
        "@type": "ImageObject",
        "url": imageUrl,
        "width": 1200,
        "height": 630
      }],
      "site_name": "SopAI"
    },
    "twitter": {
      "@type": "Website",
      "card": "summary_large_image",
      "site": "@sh20raj",
      "title": title,
      "description": description,
      "image": imageUrl
    }
  };
}




export default async function page({params}) {
  const id = params.id;
  console.log(id);
  let image = await getImage(id)
  image = image.items[0]

  return (
    <>
    <ImagePage image={image}/>
    <Feeds/>
    </>
  )
}
