import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";

export const runtime = 'edge';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "SopAI - AI Image Generator",
  description: "Images Generated by SopAI - AI Image Generator",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
<div className="fixed left-0 top-0 -z-10 h-full w-full"><div className="absolute top-0 -z-10 h-full w-full bg-white"><div className="absolute bottom-auto left-auto right-0 top-0 h-[500px] w-[500px] -translate-x-[30%] translate-y-[20%] rounded-full bg-[rgba(173,109,244,0.5)] opacity-50 blur-[80px]" /></div></div>
        <Header/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
