/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/21uSixBZEpx
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Bricolage_Grotesque } from 'next/font/google'

bricolage_grotesque({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function GeneratorPage() {
  return (
    (
    <div className="grid grid-cols-[300px_1fr] gap-6 p-6 w-full h-full">
      <div
        className="bg-gray-100 dark:bg-gray-800 rounded-lg p-6 flex flex-col gap-6 col-span-2">
        <h3 className="text-lg font-semibold">Generated Images</h3>
        <div className="grid grid-cols-4 gap-4" />
      </div>
      <div
        className="bg-gray-100 dark:bg-gray-800 rounded-lg p-6 flex flex-col gap-6">
        <div>
          <h3 className="text-lg font-semibold mb-2">Image Style</h3>
          <Select>
            <SelectTrigger className="w-full">
              <SelectValue placeholder="Select style" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="photorealistic">Photorealistic</SelectItem>
              <SelectItem value="abstract">Abstract</SelectItem>
              <SelectItem value="cartoon">Cartoon</SelectItem>
            </SelectContent>
          </Select>
        </div>
        <div>
          <h3 className="text-lg font-semibold mb-2">Resolution</h3>
          <div className="grid grid-cols-2 gap-2">
            <Input placeholder="Width" type="number" />
            <Input placeholder="Height" type="number" />
          </div>
        </div>
        <div>
          <h3 className="text-lg font-semibold mb-2">Aspect Ratio</h3>
          <Select>
            <SelectTrigger className="w-full">
              <SelectValue placeholder="Select aspect ratio" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="square">Square (1:1)</SelectItem>
              <SelectItem value="landscape">Landscape (16:9)</SelectItem>
              <SelectItem value="portrait">Portrait (9:16)</SelectItem>
            </SelectContent>
          </Select>
        </div>
        <div>
          <h3 className="text-lg font-semibold mb-2">Seed</h3>
          <Input placeholder="Enter seed value" type="number" />
        </div>
        <Button className="w-full">Generate Image</Button>
      </div>
      <div
        className="bg-gray-100 dark:bg-gray-800 rounded-lg p-6 flex flex-col gap-6">
        <div
          className="aspect-video bg-gray-200 dark:bg-gray-700 rounded-lg overflow-hidden flex items-center justify-center">
          <img
            alt="Generated Image"
            className="object-contain"
            height={450}
            src="/placeholder.svg"
            style={{
              aspectRatio: "800/450",
              objectFit: "cover",
            }}
            width={800} />
        </div>
        <div className="grid grid-cols-2 gap-4">
          <Button>Save Image</Button>
          <Button variant="outline">Regenerate</Button>
        </div>
      </div>
      
    </div>)
  );
}
