/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/4QMwabb15I6
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Judson } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

judson({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import getImages from "@/app/functions/getImages";
import Link from "next/link"

export async function ImageFeeds() {
  const images = await getImages();
  return (
    (<main className="container mx-auto py-12 px-4 md:px-6">
      <section className="mb-12">
        <h2 className="text-2xl font-bold mb-4">All Images</h2>
        <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
          {
            images.items.map((image,i)=> {

             return <ImageFeed image={image} key={i}/>
            })
            // JSON.stringify(images)
          }

          
        </div>
      </section>
   
    </main>)
  );
}


export function ImageFeed ({image}) {
  return <Link className="relative group" href={"/image/"+image.id}>
  <img
    alt="Image 1"
    className="w-full ch-60 object-cover rounded-lg group-hover:opacity-80 transition-opacity"
    height={768}
    src={image.url || "/placeholder.svg"}
    style={{
      aspectRatio: "512/768",
      objectFit: "cover",
    }}
    width={512} 
    />
  <div
    className="absolute inset-0 bg-gray-900 bg-opacity-0 group-hover:bg-opacity-50 flex flex-col items-center justify-center transition-colors">
    <div
      className="text-white text-xl font-bold opacity-0 group-hover:opacity-100 transition-opacity">
      View
    </div>
    <br />
    <div
    className="text-white text-xl font-bold opacity-0 group-hover:opacity-100 transition-opacity"
    >
      {image?.meta?.prompt?.substring(1,20)}
    </div>
  </div>
</Link>
}

export function TopFeeds() {
  return <>
  
  <section className="mb-12">
        <h2 className="text-2xl font-bold mb-4">Categories</h2>
        <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
          <Link className="relative group" href="#">
            <img
              alt="Category 1"
              className="w-full h-60 object-cover rounded-lg group-hover:opacity-80 transition-opacity"
              height={300}
              src="/placeholder.svg"
              style={{
                aspectRatio: "300/300",
                objectFit: "cover",
              }}
              width={300} />
            <div
              className="absolute inset-0 bg-gray-900 bg-opacity-0 group-hover:bg-opacity-50 flex items-center justify-center transition-colors">
              <span
                className="text-white text-xl font-bold opacity-0 group-hover:opacity-100 transition-opacity">
                Nature
              </span>
            </div>
          </Link>
          <Link className="relative group" href="#">
            <img
              alt="Category 2"
              className="w-full h-60 object-cover rounded-lg group-hover:opacity-80 transition-opacity"
              height={300}
              src="/placeholder.svg"
              style={{
                aspectRatio: "300/300",
                objectFit: "cover",
              }}
              width={300} />
            <div
              className="absolute inset-0 bg-gray-900 bg-opacity-0 group-hover:bg-opacity-50 flex items-center justify-center transition-colors">
              <span
                className="text-white text-xl font-bold opacity-0 group-hover:opacity-100 transition-opacity">
                Architecture
              </span>
            </div>
          </Link>
          <Link className="relative group" href="#">
            <img
              alt="Category 3"
              className="w-full h-60 object-cover rounded-lg group-hover:opacity-80 transition-opacity"
              height={300}
              src="/placeholder.svg"
              style={{
                aspectRatio: "300/300",
                objectFit: "cover",
              }}
              width={300} />
            <div
              className="absolute inset-0 bg-gray-900 bg-opacity-0 group-hover:bg-opacity-50 flex items-center justify-center transition-colors">
              <span
                className="text-white text-xl font-bold opacity-0 group-hover:opacity-100 transition-opacity">
                People
              </span>
            </div>
          </Link>
          <Link className="relative group" href="#">
            <img
              alt="Category 4"
              className="w-full h-60 object-cover rounded-lg group-hover:opacity-80 transition-opacity"
              height={300}
              src="/placeholder.svg"
              style={{
                aspectRatio: "300/300",
                objectFit: "cover",
              }}
              width={300} />
            <div
              className="absolute inset-0 bg-gray-900 bg-opacity-0 group-hover:bg-opacity-50 flex items-center justify-center transition-colors">
              <span
                className="text-white text-xl font-bold opacity-0 group-hover:opacity-100 transition-opacity">
                Travel
              </span>
            </div>
          </Link>
        </div>
      </section>
      <section className="mb-12">
        <h2 className="text-2xl font-bold mb-4">Popular Images</h2>
        <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
          <Link className="relative group" href="#">
            <img
              alt="Popular Image 1"
              className="w-full h-60 object-cover rounded-lg group-hover:opacity-80 transition-opacity"
              height={300}
              src="/placeholder.svg"
              style={{
                aspectRatio: "300/300",
                objectFit: "cover",
              }}
              width={300} />
            <div
              className="absolute inset-0 bg-gray-900 bg-opacity-0 group-hover:bg-opacity-50 flex items-center justify-center transition-colors">
              <span
                className="text-white text-xl font-bold opacity-0 group-hover:opacity-100 transition-opacity">
                View
              </span>
            </div>
          </Link>
          <Link className="relative group" href="#">
            <img
              alt="Popular Image 2"
              className="w-full h-60 object-cover rounded-lg group-hover:opacity-80 transition-opacity"
              height={300}
              src="/placeholder.svg"
              style={{
                aspectRatio: "300/300",
                objectFit: "cover",
              }}
              width={300} />
            <div
              className="absolute inset-0 bg-gray-900 bg-opacity-0 group-hover:bg-opacity-50 flex items-center justify-center transition-colors">
              <span
                className="text-white text-xl font-bold opacity-0 group-hover:opacity-100 transition-opacity">
                View
              </span>
            </div>
          </Link>
          <Link className="relative group" href="#">
            <img
              alt="Popular Image 3"
              className="w-full h-60 object-cover rounded-lg group-hover:opacity-80 transition-opacity"
              height={300}
              src="/placeholder.svg"
              style={{
                aspectRatio: "300/300",
                objectFit: "cover",
              }}
              width={300} />
            <div
              className="absolute inset-0 bg-gray-900 bg-opacity-0 group-hover:bg-opacity-50 flex items-center justify-center transition-colors">
              <span
                className="text-white text-xl font-bold opacity-0 group-hover:opacity-100 transition-opacity">
                View
              </span>
            </div>
          </Link>
          <Link className="relative group" href="#">
            <img
              alt="Popular Image 4"
              className="w-full h-60 object-cover rounded-lg group-hover:opacity-80 transition-opacity"
              height={300}
              src="/placeholder.svg"
              style={{
                aspectRatio: "300/300",
                objectFit: "cover",
              }}
              width={300} />
            <div
              className="absolute inset-0 bg-gray-900 bg-opacity-0 group-hover:bg-opacity-50 flex items-center justify-center transition-colors">
              <span
                className="text-white text-xl font-bold opacity-0 group-hover:opacity-100 transition-opacity">
                View
              </span>
            </div>
          </Link>
        </div>
      </section>
      <section className="mb-12">
        <h2 className="text-2xl font-bold mb-4">Newest Uploads</h2>
        <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
          <Link className="relative group" href="#">
            <img
              alt="Newest Image 1"
              className="w-full h-60 object-cover rounded-lg group-hover:opacity-80 transition-opacity"
              height={300}
              src="/placeholder.svg"
              style={{
                aspectRatio: "300/300",
                objectFit: "cover",
              }}
              width={300} />
            <div
              className="absolute inset-0 bg-gray-900 bg-opacity-0 group-hover:bg-opacity-50 flex items-center justify-center transition-colors">
              <span
                className="text-white text-xl font-bold opacity-0 group-hover:opacity-100 transition-opacity">
                View
              </span>
            </div>
          </Link>
          <Link className="relative group" href="#">
            <img
              alt="Newest Image 2"
              className="w-full h-60 object-cover rounded-lg group-hover:opacity-80 transition-opacity"
              height={300}
              src="/placeholder.svg"
              style={{
                aspectRatio: "300/300",
                objectFit: "cover",
              }}
              width={300} />
            <div
              className="absolute inset-0 bg-gray-900 bg-opacity-0 group-hover:bg-opacity-50 flex items-center justify-center transition-colors">
              <span
                className="text-white text-xl font-bold opacity-0 group-hover:opacity-100 transition-opacity">
                View
              </span>
            </div>
          </Link>
          <Link className="relative group" href="#">
            <img
              alt="Newest Image 3"
              className="w-full h-60 object-cover rounded-lg group-hover:opacity-80 transition-opacity"
              height={300}
              src="/placeholder.svg"
              style={{
                aspectRatio: "300/300",
                objectFit: "cover",
              }}
              width={300} />
            <div
              className="absolute inset-0 bg-gray-900 bg-opacity-0 group-hover:bg-opacity-50 flex items-center justify-center transition-colors">
              <span
                className="text-white text-xl font-bold opacity-0 group-hover:opacity-100 transition-opacity">
                View
              </span>
            </div>
          </Link>
          <Link className="relative group" href="#">
            <img
              alt="Newest Image 4"
              className="w-full h-60 object-cover rounded-lg group-hover:opacity-80 transition-opacity"
              height={300}
              src="/placeholder.svg"
              style={{
                aspectRatio: "300/300",
                objectFit: "cover",
              }}
              width={300} />
            <div
              className="absolute inset-0 bg-gray-900 bg-opacity-0 group-hover:bg-opacity-50 flex items-center justify-center transition-colors">
              <span
                className="text-white text-xl font-bold opacity-0 group-hover:opacity-100 transition-opacity">
                View
              </span>
            </div>
          </Link>
        </div>
      </section>
      </>
}