/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/xx4AcVzKftt
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"

export function ImagePage({image}) {
  return (
    (<main
      className="flex flex-col items-center justify-center min-h-[100dvh] px-4 md:px-6 py-12 md:py-24 lg:py-32">
      <div className=" h-full w-full  gap-8 flex flex-row justify-center  ">
        {/* <div className="text-center space-y-2">
          <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">AI Image Viewer</h1>
          <p className="text-gray-500 md:text-xl dark:text-gray-400">
            Explore the latest AI-generated images and learn about the technology behind them.
          </p>
        </div> */}
        <div className="bg-gray-100 dark:bg-gray-800 rounded-lg  h-full w-1/2">
          <img
            alt="AI-generated image"
            className="w-full h-auto object-cover rounded-lg"
            // height={6}
            // height={768}
            src={image.url || "/placeholder.svg"}
            // style={{
            //   aspectRatio: "512/768",
            //   objectFit: "cover",
            // }}
            // width="20px"
            />
        </div>
        <div className="bg-gray-100 dark:bg-gray-800 rounded-lg h-full p-10 w-1/3">
          <div>
            <h2 className="text-lg font-medium inline-block">Image Details</h2>
            <div className="download inline-block float-right">
              <Button>
              <a href={image.url} download={"sopai.png"}>Download</a>
              </Button>
            </div>
            <div className="line"></div>
            </div>
          <div className="flex flex-col gap-8 my-10">
            <div>
              <p className="text-sm text-gray-500 dark:text-gray-400">AI Model</p>
              <p>Stable Diffusion v2</p>
            </div>
          
            <div>
              <p className="text-sm text-gray-500 dark:text-gray-400">Generation Date</p>
              <p>May 8, 2024</p>
            </div>
            <div>
              <p className="text-sm text-gray-500 dark:text-gray-400">Prompt</p>
              <p>{
              image.meta.prompt
              }</p>
            </div>
            <div>
              <p className="text-sm text-gray-500 dark:text-gray-400">Resolution</p>
              <p>800 x 600 pixels</p>
            </div>
          </div>
          <div>
            <h2 className="text-lg font-medium">Tags</h2>
            <div className="line"></div>
            <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-2 mt-10">
              <Button size="sm" variant="outline">
                Surreal
              </Button>
              <Button size="sm" variant="outline">
                Landscape
              </Button>
              <Button size="sm" variant="outline">
                Floating Islands
              </Button>
              <Button size="sm" variant="outline">
                Colorful Sky
              </Button>
              <Button size="sm" variant="outline">
                Dream
              </Button>
              <Button size="sm" variant="outline">
                Imagination
              </Button>
            </div>
          </div>
        </div>
      </div>
    </main>)
  );
}
