{/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ATDKlhED8vL
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/}
import Link from "next/link"
import { Input } from "@/components/ui/input"
import Header from "./header";
import { ImageFeeds } from "./image-feeds";

export function MainPage() {
  return (<>
  <Header/>
    <ImageFeeds/>
    <main className="container mx-auto px-4 md:px-6 py-8">
      <div className="mb-6">
        <h1 className="text-3xl font-bold text-gray-900 dark:text-gray-50">3D Models</h1>
        <p className="text-gray-600 dark:text-gray-400">Browse our collection of high-quality 3D models.</p>
      </div>
      <div
        className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
        <div className="relative group overflow-hidden rounded-lg">
          <Link className="absolute inset-0 z-10" href="#">
            <span className="sr-only">View</span>
          </Link>
          <img
            alt="3D Model 1"
            className="object-cover w-full h-60"
            height={300}
            src="/placeholder.svg"
            style={{
              aspectRatio: "400/300",
              objectFit: "cover",
            }}
            width={400} />
          <div
            className="absolute inset-0 bg-gray-900 bg-opacity-50 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity">
            <div className="text-white text-center space-y-2">
              <h3 className="text-lg font-semibold">Futuristic Robot</h3>
              <p className="text-sm">A highly detailed 3D model of a futuristic robot.</p>
            </div>
          </div>
        </div>
        <div className="relative group overflow-hidden rounded-lg">
          <Link className="absolute inset-0 z-10" href="#">
            <span className="sr-only">View</span>
          </Link>
          <img
            alt="3D Model 2"
            className="object-cover w-full h-60"
            height={300}
            src="/placeholder.svg"
            style={{
              aspectRatio: "400/300",
              objectFit: "cover",
            }}
            width={400} />
          <div
            className="absolute inset-0 bg-gray-900 bg-opacity-50 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity">
            <div className="text-white text-center space-y-2">
              <h3 className="text-lg font-semibold">Sci-Fi Weapon</h3>
              <p className="text-sm">A high-tech sci-fi weapon with intricate details.</p>
            </div>
          </div>
        </div>
        <div className="relative group overflow-hidden rounded-lg">
          <Link className="absolute inset-0 z-10" href="#">
            <span className="sr-only">View</span>
          </Link>
          <img
            alt="3D Model 3"
            className="object-cover w-full h-60"
            height={300}
            src="/placeholder.svg"
            style={{
              aspectRatio: "400/300",
              objectFit: "cover",
            }}
            width={400} />
          <div
            className="absolute inset-0 bg-gray-900 bg-opacity-50 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity">
            <div className="text-white text-center space-y-2">
              <h3 className="text-lg font-semibold">Fantasy Creature</h3>
              <p className="text-sm">A mythical creature with intricate details and textures.</p>
            </div>
          </div>
        </div>
        <div className="relative group overflow-hidden rounded-lg">
          <Link className="absolute inset-0 z-10" href="#">
            <span className="sr-only">View</span>
          </Link>
          <img
            alt="3D Model 4"
            className="object-cover w-full h-60"
            height={300}
            src="/placeholder.svg"
            style={{
              aspectRatio: "400/300",
              objectFit: "cover",
            }}
            width={400} />
          <div
            className="absolute inset-0 bg-gray-900 bg-opacity-50 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity">
            <div className="text-white text-center space-y-2">
              <h3 className="text-lg font-semibold">Vintage Car</h3>
              <p className="text-sm">A highly detailed 3D model of a vintage car.</p>
            </div>
          </div>
        </div>
        <div className="relative group overflow-hidden rounded-lg">
          <Link className="absolute inset-0 z-10" href="#">
            <span className="sr-only">View</span>
          </Link>
          <img
            alt="3D Model 5"
            className="object-cover w-full h-60"
            height={300}
            src="/placeholder.svg"
            style={{
              aspectRatio: "400/300",
              objectFit: "cover",
            }}
            width={400} />
          <div
            className="absolute inset-0 bg-gray-900 bg-opacity-50 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity">
            <div className="text-white text-center space-y-2">
              <h3 className="text-lg font-semibold">Futuristic Building</h3>
              <p className="text-sm">A highly detailed 3D model of a futuristic building.</p>
            </div>
          </div>
        </div>
        <div className="relative group overflow-hidden rounded-lg">
          <Link className="absolute inset-0 z-10" href="#">
            <span className="sr-only">View</span>
          </Link>
          <img
            alt="3D Model 6"
            className="object-cover w-full h-60"
            height={300}
            src="/placeholder.svg"
            style={{
              aspectRatio: "400/300",
              objectFit: "cover",
            }}
            width={400} />
          <div
            className="absolute inset-0 bg-gray-900 bg-opacity-50 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity">
            <div className="text-white text-center space-y-2">
              <h3 className="text-lg font-semibold">Fantasy Landscape</h3>
              <p className="text-sm">A highly detailed 3D model of a fantasy landscape.</p>
            </div>
          </div>
        </div>
      </div>
    </main>
    <footer className="bg-gray-100 dark:bg-gray-800 py-6 mt-8">
      <div
        className="container mx-auto px-4 md:px-6 flex items-center justify-between">
        <p className="text-gray-600 dark:text-gray-400 text-sm">© 2024 SopAI. All rights reserved.</p>
        <nav className="flex items-center gap-4">
          <Link
            className="text-gray-600 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50 text-sm"
            href="#">
            Terms of Service
          </Link>
          <Link
            className="text-gray-600 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50 text-sm"
            href="#">
            Privacy Policy
          </Link>
          <Link
            className="text-gray-600 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50 text-sm"
            href="#">
            Contact
          </Link>
        </nav>
      </div>
    </footer>
  </>);
}
