{/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ATDKlhED8vL
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/}
import Link from "next/link"
import Image from "next/image"
import { ImageFeeds } from "./image-feeds"
import CivitaiPage from "@/app/civitai/page"

export function MainPage() {
  return (
    <div className="flex flex-col items-center min-h-screen py-12 px-4 sm:px-6 lg:px-8">
      <div className="w-full max-w-4xl space-y-12">
        <div className="text-center space-y-4">
          <h1 className="text-4xl font-bold tracking-tight text-gray-900 dark:text-gray-50 sm:text-5xl md:text-6xl">
            Create Amazing Images with AI
          </h1>
          <p className="max-w-2xl mx-auto text-xl text-gray-500 dark:text-gray-400">
            Transform your ideas into stunning visuals instantly
          </p>
        </div>

        <div className="flex justify-center">
          <div className="w-full max-w-2xl relative">
            <input
              type="text"
              className="w-full h-12 px-4 rounded-full border border-gray-300 dark:border-gray-700 focus:outline-none focus:ring-2 focus:ring-purple-500 dark:bg-gray-800 dark:text-gray-100"
              placeholder="Describe the image you want to create..."
              aria-label="Image description input"
            />
            <button
              className="absolute right-2 top-1/2 -translate-y-1/2 px-6 py-2 bg-purple-600 text-white rounded-full hover:bg-purple-700 focus:outline-none focus:ring-2 focus:ring-purple-500 focus:ring-offset-2 transition-colors"
              aria-label="Generate image"
            >
              Generate
            </button>
          </div>
        </div>

        <section aria-label="Recent generations" className="space-y-6">
          <h2 className="text-2xl font-semibold text-gray-900 dark:text-gray-50">Recent Generations</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
            {[1, 2, 3].map((item) => (
              <article key={item} className="group relative rounded-lg overflow-hidden shadow-lg transition-transform hover:scale-[1.02]">
                <Link href="#" className="block aspect-square relative" aria-label={`View generated image ${item}`}>
                  <Image
                    src="/placeholder.svg"
                    alt={`AI Generated Image ${item}`}
                    fill
                    className="object-cover"
                    sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
                    priority={item === 1}
                    loading={item === 1 ? 'eager' : 'lazy'}
                  />
                  <div className="absolute inset-0 bg-black bg-opacity-40 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center">
                    <span className="text-white text-sm font-medium">View Details</span>
                  </div>
                </Link>
              </article>
            ))}
          </div>
        </section>
      </div>
      <CivitaiPage/>
      {/* <ImageFeeds /> */}
    </div>
  )
}
